app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import DataRequired

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')
class BlogForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    category = SelectField('Category', choices=[('Technology','Technology'),('Health','Health'),('Food','Food '),('Lifestyle','lifestyle'),],validators=[DataRequired()])
    post = TextAreaField('Your Story', validators=[DataRequired()])
    submit = SubmitField('Post Blog')
class CommentForm(FlaskForm):
    comment = TextAreaField('Leave a comment',validators=[DataRequired()])
    submit = SubmitField('Comment')      

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from . import main
from flask import render_template,request,redirect,url_for,abort,flash
from ..models import  Blog, User,Comment,Subscriber
from .forms import UpdateProfile,BlogForm,CommentForm
from .. import db,photos
from flask_login import login_required,current_user
from app.request import get_quotes
from ..email import mail_message
from . import main



@main.route('/')
def index():
    quotes = get_quotes()
    blogs = Blog.query.all()
    technology  = Blog.query.filter_by(category = 'Technology').all() 
    health = Blog.query.filter_by(category = 'Health').all()
    lifestyle= Blog.query.filter_by(category = 'Lifestyle').all()
    food= Blog.query.filter_by(category = 'Food').all()


    return render_template('main/index.html',blogs =blogs,technology =technology, health = health, lifestyle=  lifestyle, food= food,quotes=quotes)
# @main.route('/')
# def index():


#     return render_template('main/index.html')

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)    
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)    

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/create_new', methods = ['POST','GET'])
@login_required
def new_blog():
    subscribers = Subscriber.query.all()
    form = BlogForm()
    if form.validate_on_submit():
        title = form.title.data
        post = form.post.data
        category = form.category.data
        user_id = current_user
        new_blog_object = Blog(post=post,user_id=current_user._get_current_object().id,category=category,title=title)
        new_blog_object.save_p()
        for subscriber in subscribers:
            mail_message("New Blog Post","email/welcome_user",subscriber.email,new_blog_object=new_blog_object)
        return redirect(url_for('main.index'))
        
    return render_template('main/blog.html', form = form)

@main.route('/comment/<int:blog_id>', methods = ['POST','GET'])
def comment(blog_id):
    form = CommentForm()
    blog = Blog.query.get(blog_id)
    all_comments = Comment.query.filter_by(blog_id = blog_id).all()
    if form.validate_on_submit():
        comment = form.comment.data 
        blog_id = blog_id
        new_comment = Comment(comment = comment,blog_id = blog_id)
        new_comment.save_c()
        return redirect(url_for('.comment', blog_id = blog_id))
    return render_template('main/comment.html', form =form,  blog =  blog,all_comments=all_comments) 

@main.route('/blog/<blog_id>/delete', methods = ['POST'])
@login_required
def delete_post(blog_id):
    blog = Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(403)
    blog.delete()
    flash("You have deleted your Blog succesfully!")
    return redirect(url_for('main.index'))

@main.route('/blog/<blog_id>/update', methods = ['GET','POST'])
@login_required
def updateblog(blog_id):
    blog = Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(403)
    form = BlogForm()
    if form.validate_on_submit():
        blog.title = form.title.data
        blog.post = form.post.data
        db.session.commit()
        flash("You have updated your Blog!")
        return redirect(url_for('main.blog',id = blog.id)) 
    if request.method == 'GET':
        form.title.data = blog.title
        form.post.data = blog.post
    return render_template('edit.html', form = form)


@main.route('/subscribe',methods = ['POST','GET'])
def subscribe():
    email = request.form.get('subscriber')
    new_subscriber = Subscriber(email = email)
    new_subscriber.save_subscriber()
    mail_message("Subscribed to janeffer'sblog","email/welcome_user",new_subscriber.email,new_subscriber=new_subscriber)
    flash('Sucessfuly subscribed')
    return redirect(url_for('main.index'))

app/templates/main/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css" rel="stylesheet" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <!-- Styles block -->
    <title>JANEFFER'SBLOG</title>
</head>

<body>
    {% extends 'bootstrap/base.html'%}

    {% include 'main/navbar.html' %}


    {% block content %}


    

    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>
    <!-- booostrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


</body>

</html>
{% endblock %}

app/templates/main/blog.html
{% extends 'main/base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}
<div class="container-md ">
    <div  id="pitchadd"  >  
        <div class=" row" >
                
                <div class="col-md-2"></div>
                <div class="col-md-8" id="postform">
                    <h2 class="text-center">Add Your Blog Here!</h2>
                    {{wtf.quick_form(form)}}
                </div>
                <div class="col-md-2"></div>
        </div>
</div>
</div>
  
   
{% endblock%}

app/templates/main/comment.html
  
{% extends 'main/base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container" id="comments" >
        <div class="row">

            {% if all_comments %}
                <div class="col-md-7" >
                    <h3 class="text-center" id="coms">All comments for the post</h3>
                    {% for comment in all_comments %}
                       <div class="card w-90 mb-3" >
                           <div class="card-body">
                            <h5>{{comment.blog.title}}</h5>
                             <p class="card-title">{{ comment.comment }}</p>
                           </div>
                       </div>
                    {% endfor %}
                   </div>
                   <div class="col-md-5  commentform" >

                        {{wtf.quick_form(form)}}
                   </div>
               </div>
            {%else%}
            <div class="card w-90 mb-3">
                <div class="card-body">
                  <p class="card-title">No Comments for this post. leave Your Comment</p>
                </div>
            </div> 
            <div class="col-md-5">
                    {{wtf.quick_form(form)}}
                </div>
            {%endif%}
    </div>
   
{% endblock%}

app/templates/main/errors.html
<h3>errors page</h3>

app/templates/main/index.html
{% extends 'main/base.html'%}
{% import 'main/macros.html' as macro %}


{% block content %}

<div class="container h-100" id="header">
  <div class="row">
    <div class="col-md-6 h-100" id="col1">
      <img src="{{url_for('static', filename='1.jpg')}}" />

       </div>
    <div class="col-md-6 h-100" id="col2">
      <h3> Unleash Your <br> Creativity</h3>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error vitae delectus velit, dolores officia eius
        asperiores unde facere nisi incidunt perferendis est voluptatum consequuntur quasi quidem dignissimos sequi
        deleniti eaque.</p>
      <div class="btns">
        <a href="#about-header">
          <button type="button" class="btn btn-danger btn-lg">Learn More!</button>
        </a>

      </div>
    </div>
  </div>
</div>
<div class="container">
  <h3 class="text-center" id="abouttitle">Our Blogs</h3>
  <div class="container">
    <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
      <li class="nav-item">
        <a id="btns" class="nav-link" data-toggle="tab" href="#blogs"><strong>All Blogs</strong> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-outline-dark" id="btns" data-toggle="tab" href="#technology">Technology Blogs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="btns" data-toggle="tab" href="#food">Food Blogs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="btns" data-toggle="tab" href="#lifestyle">Lifestyle Blogs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="btns" data-toggle="tab" href="#health">Health Blogs</a>
      </li>
    </ul>
  </div>
  <div class="tab-content">
    <div class="container tab-pane active" id="blogs"><br>
      {{ macro.display(blogs) }}
    </div>
    <div class="container tab-pane fade" id="technology"><br>
      {{ macro.display(technology)}}
    </div>
    <div class="container tab-pane fade" id="food"><br>
      {{ macro.display(food) }}
    </div>
    <div class="container tab-pane fade" id="lifestyle"><br>
      {{ macro.display(lifestyle) }}

    </div>
    <div class="container tab-pane fade" id="health"><br>
      {{ macro.display(health) }}

    </div>
  </div>
</div>
</div>
{% if quotes %}

<div class="container" id="qoutes">
  <div class="row">
    <h3 class="text-center text-white" id="h3">Get Inspired By Quote Of The Day</h3>

    <div class="col-md-6 h-100" id="quoteid">
      <div class="card cardquote" id="quote2">
        <div class="card-title" id="quote">
          <h4>A quote by: <span style="color: rgb(3, 3, 3)">{{quotes.author}}</span> </h4>
        </div>
        <p class="card-text">{{quotes.quote}}</p>
        <a href="{{quotes.permalink}}">
          <button type="button" class="btn btn-danger">Quote Link!!!</button>
        </a>
      </div>
    </div>
    <div class="col-md-6 h-100" id="forimg">
     
    </div>
  </div>



</div>
<div class="container">
  <h3 id="about-header" class="text-center">About</h3>
  <div class="row">
    <div class="col-md-3">
      
    </div>
    <div class="col-md-6" id="card2">
      <h3>WELCOME TO JANEFFER'SBLOG, We're glad thaat you are here</h3>
      <p>This is a personal blogging website where we create and share opinions and our users can read and comment on
        them. Additionally, we displays random quotes to inspire our users. </p>
    </div>
    <div class="col-md-3">

    </div>
  </div>
</div>
{% endif %}
<div class="container mt-5" id="email-cont">
  <h3>Subscribe To Our Blog Posts</h3>
  {% for message in get_flashed_messages() %}
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %}
  <form class="form-inline" action="{{url_for('main.subscribe')}}" method="POST">
    <div class="md-form form-group" id="email">
      <label class="white-color">Email Address...</label>
      <input type="email" class="form-control " name="subscriber" required>
    </div>
    <div class="md-form form-group">
      <button class="btn btn-sm btn-outline-info" id="subs">Subscribe</button>
    </div>
  </form>
</div>
<footer class="page-footer bg-dark text-white font-small blue mt-5">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2022 Copyright: janeffer'sblog
  </div>

</footer>
{% endblock%}  

app/templates/main/macros.html
  
{% macro display(blogs) %}

<div class="container-fluid">
    <div class="row">
        {% if blogs %}
        {% for category in blogs %}
        <div class="col-md-12">
            <div class="thumbnail" id="carded">
                <h5 class="card-header text-center" id="title">{{category.title}}</h5>
                <div class="card-body">
                    <p class="post"> {{category.post}}</p>
                    <p class="text-center" id="cate"> Category: {{category.category}}</p>
                    <footer class="blockquote-footer text-center"> Posted by: {{category.user.username}}</footer>
                    <div>
                        <span class="foot">{{category.comment.count()}} Comments</span>
                    </div>
                    <a href="{{url_for('main.comment',blog_id = category.id)}}" class="btn btn-danger" id="comment"> Comment</a>
                    <a href="#"><i class="btn btn-warning">DELETE</i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="$"><i class="btn btn-warning">EDIT</i></a> 
                </div>
            </div>
        </div>

        {% endfor %}
        {% else %}
        <div class="card w-90 mb-3">
            <div class="card-body">

                <p class="card-title">Category Has 0 posts</p>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endmacro %}

app/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#" id="logo">JANEFFER'SBLOG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse ms-auto" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.index')}}">Blogs</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.new_blog')}}">New Blog</a>
        </li>
        {% endif %}
      </ul>
      <div>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
    
          <li style="color:white;padding:15px;">{{current_user.username}}</li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
          {%endif%}
        </ul>
      </div>
    </div>
   
  </nav>

app/templates/main/showblogs.html
{% extends 'main/base.html'%}
{% import 'macros.html' as macro %}
{% block content%}
 <div class="container">
    <div class="tab-content">
      <div  class="container tab-pane active" id="all"><br>
          {{ macro.display(blogs) }}
      </div>
      <div  class="container tab-pane fade" id="event"><br>
          {{ macro.display(technology)}}
      </div>
      <div  class="container tab-pane fade" id="jobs"><br>
          {{ macro.display(food) }}
      </div>
      <div  class="container tab-pane fade" id="ads"><br>
          {{ macro.display(lifestyle) }}
          
      </div>
      <div  class="container tab-pane fade" id="ads"><br>
        {{ macro.display(health) }}
        
    </div>
  </div>
  </div>
  {% endblock%}